# Generated by Django 3.2.8 on 2021-10-10 19:28

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0008_auto_20211010_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='category',
            new_name='pic_category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='location',
            new_name='pic_location',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='pic_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='picture',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='picture'),
            preserve_default=False,
        ),
    ]
