# Generated by Django 3.2.8 on 2021-10-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0009_auto_20211010_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='pic_location',
            new_name='location',
        ),
    ]
