# Generated by Django 3.2.8 on 2021-10-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0011_alter_image_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='picture',
            new_name='image',
        ),
    ]
