# Generated by Django 3.2.8 on 2021-10-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picha', '0012_rename_picture_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='picture',
        ),
    ]
